language: python
python:
  - "2.7"
  - "3.6"
node_js:
  - 6
  - 8
  - 10
  - 12
services:
  - rabbitmq
  - postgresql
before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres
install:
  - pip install -r requirements.txt
script: python manage.py test
env:
  - AWS_ENABLED=yes
